setwd("C:/Users/lhj/Desktop/TCD/金融模型分析") 
library (xts)
library (zoo)
library (PerformanceAnalytics)
library(pastecs)
library(tseries)
library(corrplot)
library(tseries)
library(compiler)
library("FactoMineR")
library("factoextra")
library (psych) # the library for factor analysis
# install.packages("GPArotation")
library (GPArotation)
